### PR TITLE
Improve variable detection

### LINKED ISSUE #9: Variables not detected when followed by end of collection or dictionary
Variables (`$b` below) followed by either a right paranthese or right curly brace are not detected

image

Suggestion:
1. Trim `)`, `}` and `]` [here](https://github.com/TylerLeonhardt/vscode-inline-values-powershell/blob/a9d4c3663090c40b602e6ba0b8dd3778f40df9a8/src/powerShellVariableInlineValuesProvider.ts#L32)

2. Or update regex from `\S+` to valid char sets defined [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_variables?view=powershell-7.2#variable-names-that-include-special-characters) in the last to groups ($scope:variable and $variable):
Lu - UppercaseLetter
Ll - LowercaseLetter
Lt - TitlecaseLetter
Lm - ModifierLetter
Lo - OtherLetter
Nd - DecimalDigitNumber

### PR DESCRIPTION
**Pull request by fflaten**
Rewritten variable detection to:
- Validate variable names against character rules defined in [about_Variables](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_variables?view=powershell-5.1#variable-names-that-include-special-characters)
- Validate scope in scoped variables
- Fix special character variable matching. Current version used greedy match that didn't stop at the correct `}`
- Detect variables inside arrays, subexpression, dictionary/hashtable or variable used as dict key

Other changes:
- Lots of variable detection tests added for better coverage
- Moved patterns and other constants to class-level

Fix #9

### CODE REVIEW

**Comment by fflaten** [comment]
@TylerLeonhardt Please review. Learning TS/JS as I go here 🙂

**Comment by fflaten** [comment]
Remaining scopes not added as supported:

  - **workflow**: Ignored as it's niche and not available in cross-platform.
  - **function**: Would require expression, but ignored as it's usually multi-line, so not suitable.
  - Can be implemented using expression values (see #12)
    - **Alias**: Aliases defined in the current scope
    - **Env**: Environment variables defined in the current scope

**Review by TylerLeonhardt — APPROVED** [review]
Looks fantastic! Awesome work 👏

**Comment by TylerLeonhardt** [comment]
This has now been published in 0.0.6

**Pull request merged**
